### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by malique-bodie** [newalina/art-gen#22]
When running server run into: ImportError: cannot import name 'escape' from 'jinja2' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/jinja2/__init__.py).

**Comment by momothain** [comment]
tried to reduce w/ pip-reqs package but

```bash
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

**Comment by momothain** [comment]
tried to reinstall requirements one by one from scratch but google import does not fulfill

```bash
(.venv) ➜  flask git:(momothain) ✗ python3 pip_semantic_freeze.py 
(.venv) ➜  flask git:(momothain) ✗ pipi google                    
Requirement already satisfied: google in ./.venv/lib/python3.12/site-packages (3.0.0)
Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.12/site-packages (from google) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in ./.venv/lib/python3.12/site-packages (from beautifulsoup4->google) (2.5)
(.venv) ➜  flask git:(momothain) pipi google-cloud 
fRequirement already satisfied: google-cloud in ./.venv/lib/python3.12/site-packages (0.34.0)
las%                                                                                                                                                        
(.venv) ➜  flask git:(momothain) flask run
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/momothain/cs234/art-gen/code/Backend/BackEndCommandInterface/flask/.venv/lib/python3.12/site-packages/flask/cli.py", line 245, in locate_app
    __import__(module_name)
  File "/Users/momothain/cs234/art-gen/code/Backend/BackEndCommandInterface/flask/app.py", line 17, in <module>
    from google.cloud import storage
ModuleNotFoundError: No module named 'google'

(.venv) ➜  flask git:(momothain) 
```

**Comment by momothain** [comment]
tried transforming to ~= semantic equivalent requirement specs but didn't help

```python
import subprocess

# Run pip freeze and capture the output
result = subprocess.run(['pip', 'freeze'], stdout=subprocess.PIPE, text=True)
packages = result.stdout.split('\n')

# Create a new requirements file
with open('requirements_tilde.txt', 'w') as f:
    for package in packages:
        if package:
            name, version = package.split('==')
            # Generate compatible release specifier
            major, minor, *_ = version.split('.')
            f.write(f'{name}~={major}.{minor}\n')
```

```.txt
beautifulsoup4~=4.12
bidict~=0.23
blinker~=1.8
certifi~=2024.2
charset-normalizer~=3.3
click~=8.1
Flask~=3.0
Flask-Cors~=4.0
Flask-SocketIO~=5.3
google~=3.0
google-cloud~=0.34
h11~=0.14
idna~=3.7
itsdangerous~=2.2
Jinja2~=3.1
MarkupSafe~=2.1
python-engineio~=4.9
python-socketio~=5.11
requests~=2.31
simple-websocket~=1.0
soupsieve~=2.5
urllib3~=2.2
Werkzeug~=3.0
wsproto~=1.2
```

**Comment by momothain** [comment]
jinja2 gets installed with just pip install flask, something about not used in the file but as an interface for external dependencies
